sales:
  outputs:
    dev:
      type: snowflake
      account: lxdzptn-eu09470
      user: momod
      password: Mo123456789+++
      role: ACCOUNTADMIN
      database: sales
      schema: "layer"
      warehouse: sales_WH
      threads: 2
  target: dev
